language: go

sudo: false

services:
    - docker

go:
    - 1.8.x
    - tip

env:
    global:
        TWITTER_CONSUMER_KEY: key
        TWITTER_CONSUMER_SECRET: secret
        TWITTER_ACCESS_KEY: key
        TWITTER_ACCESS_SECRET: secret
        WHOISXML_USER: user
        WHOISXML_PASSWORD: pass

branches:
    except:
        - gh-pages
        - site

before_install:
    - mkdir -p $HOME/bin
    - curl -sL http://get.binhq.io/gitbin | DEST=$HOME/bin bash
    - gitbin get Masterminds/glide 0.12.3 -o $HOME/bin
    - make envcheck

install: make setup

before_script:
    - export VERSION=${TRAVIS_TAG:-$TRAVIS_BRANCH}
    - export $(make varexport-DOCKER_IMAGE)

script:
    - make ARGS="-tags='acceptance integration' -v" check
    - if [[ $TRAVIS_TAG = "$VERSION" ]]; then export DOCKER_LATEST=true; fi
    - make docker

deploy:
    provider: script
    skip_cleanup: true
    script: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push $DOCKER_IMAGE
    on:
        all_branches: true
        condition: $TRAVIS_GO_VERSION =~ ^1\.8(\.[0-9]+)?$
