// Code generated by protoc-gen-go.
// source: nomine.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	nomine.proto

It has these top-level messages:
	NameCheckRequest
	NameCheckResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result int32

const (
	Result_AVAILABLE   Result = 0
	Result_UNAVAILABLE Result = 1
	Result_UNKOWN      Result = 2
)

var Result_name = map[int32]string{
	0: "AVAILABLE",
	1: "UNAVAILABLE",
	2: "UNKOWN",
}
var Result_value = map[string]int32{
	"AVAILABLE":   0,
	"UNAVAILABLE": 1,
	"UNKOWN":      2,
}

func (x Result) String() string {
	return proto.EnumName(Result_name, int32(x))
}
func (Result) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NameCheckRequest struct {
	Name     string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Services []string `protobuf:"bytes,2,rep,name=services" json:"services,omitempty"`
}

func (m *NameCheckRequest) Reset()                    { *m = NameCheckRequest{} }
func (m *NameCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*NameCheckRequest) ProtoMessage()               {}
func (*NameCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NameCheckRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NameCheckRequest) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

type NameCheckResponse struct {
	Results map[string]Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=nomine.Result"`
}

func (m *NameCheckResponse) Reset()                    { *m = NameCheckResponse{} }
func (m *NameCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*NameCheckResponse) ProtoMessage()               {}
func (*NameCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NameCheckResponse) GetResults() map[string]Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*NameCheckRequest)(nil), "nomine.NameCheckRequest")
	proto.RegisterType((*NameCheckResponse)(nil), "nomine.NameCheckResponse")
	proto.RegisterEnum("nomine.Result", Result_name, Result_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Nomine service

type NomineClient interface {
	Check(ctx context.Context, in *NameCheckRequest, opts ...grpc.CallOption) (*NameCheckResponse, error)
}

type nomineClient struct {
	cc *grpc.ClientConn
}

func NewNomineClient(cc *grpc.ClientConn) NomineClient {
	return &nomineClient{cc}
}

func (c *nomineClient) Check(ctx context.Context, in *NameCheckRequest, opts ...grpc.CallOption) (*NameCheckResponse, error) {
	out := new(NameCheckResponse)
	err := grpc.Invoke(ctx, "/nomine.Nomine/Check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Nomine service

type NomineServer interface {
	Check(context.Context, *NameCheckRequest) (*NameCheckResponse, error)
}

func RegisterNomineServer(s *grpc.Server, srv NomineServer) {
	s.RegisterService(&_Nomine_serviceDesc, srv)
}

func _Nomine_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomineServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nomine.Nomine/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomineServer).Check(ctx, req.(*NameCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nomine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nomine.Nomine",
	HandlerType: (*NomineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Nomine_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nomine.proto",
}

func init() { proto.RegisterFile("nomine.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x51, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x75, 0x5b, 0xa9, 0x32, 0x20, 0x96, 0x39, 0xd5, 0xc6, 0x43, 0xd3, 0x18, 0xd3, 0x70, 0x80,
	0x04, 0x3d, 0x18, 0x4e, 0x82, 0xe1, 0xa0, 0x92, 0x92, 0x34, 0x41, 0xa3, 0xb7, 0x95, 0x4c, 0xb0,
	0x01, 0x76, 0x6b, 0xb7, 0x25, 0xe1, 0xea, 0x2f, 0xf8, 0x05, 0x7e, 0x93, 0xbf, 0xe0, 0x87, 0x18,
	0xba, 0xa0, 0x24, 0xea, 0x6d, 0xe6, 0xcd, 0x9b, 0xb7, 0xef, 0xed, 0x40, 0x55, 0xc8, 0x79, 0x2c,
	0xa8, 0x99, 0xa4, 0x32, 0x93, 0x68, 0xe9, 0xce, 0x3d, 0x9e, 0x48, 0x39, 0x99, 0x51, 0x8b, 0x27,
	0x71, 0x8b, 0x0b, 0x21, 0x33, 0x9e, 0xc5, 0x52, 0x28, 0xcd, 0xf2, 0x7b, 0x60, 0x87, 0x7c, 0x4e,
	0x57, 0xcf, 0x34, 0x9e, 0x46, 0xf4, 0x92, 0x93, 0xca, 0x10, 0x61, 0x57, 0xf0, 0x39, 0x39, 0xcc,
	0x63, 0x41, 0x39, 0x2a, 0x6a, 0x74, 0x61, 0x5f, 0x51, 0xba, 0x88, 0xc7, 0xa4, 0x1c, 0xc3, 0x33,
	0x83, 0x72, 0xf4, 0xdd, 0xfb, 0xef, 0x0c, 0xea, 0x5b, 0x22, 0x2a, 0x91, 0x42, 0x11, 0x5e, 0xc2,
	0x5e, 0x4a, 0x2a, 0x9f, 0x65, 0xca, 0x61, 0x9e, 0x19, 0x54, 0xda, 0xa7, 0xcd, 0xb5, 0xbf, 0x5f,
	0xdc, 0x66, 0xa4, 0x89, 0x7d, 0x91, 0xa5, 0xcb, 0x68, 0xb3, 0xe6, 0xde, 0x40, 0x75, 0x7b, 0x80,
	0x36, 0x98, 0x53, 0x5a, 0xae, 0x6d, 0xad, 0x4a, 0x3c, 0x81, 0xd2, 0x82, 0xcf, 0x72, 0x72, 0x0c,
	0x8f, 0x05, 0xb5, 0x76, 0x6d, 0xf3, 0x82, 0x5e, 0x8b, 0xf4, 0xb0, 0x63, 0x5c, 0xb0, 0xc6, 0x39,
	0x58, 0x1a, 0xc4, 0x03, 0x28, 0x77, 0xef, 0xba, 0xd7, 0x83, 0x6e, 0x6f, 0xd0, 0xb7, 0x77, 0xf0,
	0x10, 0x2a, 0xa3, 0xf0, 0x07, 0x60, 0x08, 0x60, 0x8d, 0xc2, 0xdb, 0xe1, 0x7d, 0x68, 0x1b, 0xed,
	0x07, 0xb0, 0xc2, 0x42, 0x11, 0x87, 0x50, 0x2a, 0x2c, 0xa3, 0xf3, 0x47, 0x8a, 0xe2, 0xdb, 0xdc,
	0xa3, 0x7f, 0xf3, 0xf9, 0xf5, 0xd7, 0x8f, 0xcf, 0x37, 0xa3, 0xe2, 0x5b, 0xad, 0xf1, 0x0a, 0xef,
	0xb0, 0x46, 0xaf, 0xf4, 0x68, 0xf2, 0x24, 0x7e, 0xb2, 0x8a, 0x33, 0x9c, 0x7d, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x82, 0x12, 0x81, 0x8e, 0xbc, 0x01, 0x00, 0x00,
}
